### ISSUE TITLE
Disable DNS Prefetching

### ISSUE THREAD

**Issue by prov3it** [TheCreeper/PrivacyFox#1]
Hi,
im missing the option where DNS Prefetching is getting disabled. It appears that i can have a great impact on your privacy.

Do read: https://www.usenix.org/legacy/event/leet10/tech/full_papers/Krishnan.pdf & https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching

**Comment by Flikofbluelight747** [comment]
Thank you! I tell me if you need help.
